development:
  adapter: postgresql
  encoding: unicode
  database: itcursos_development
  pool: 5
  username: itcursos
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: itcursos_test
  pool: 5
  username: itcursos
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: itcursos_development
  pool: 5
  username: itcursos
  password: